; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:nodemcu_serial]
platform = espressif8266@^3.2.0
board = nodemcu
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    adafruit/Adafruit ADS1X15 @ ^2.4.0
    ArduinoJson @ ^6.21.3
    lorol/LittleFS_esp32 @ ^1.0.6
    knolleary/PubSubClient @ ^2.8

; File System Settings
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.4m2m.ld

[env:nodemcu_wifi_mancave]
platform = espressif8266@^3.2.0
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    adafruit/Adafruit ADS1X15 @ ^2.4.0
    ArduinoJson @ ^6.21.3
    lorol/LittleFS_esp32 @ ^1.0.6
    knolleary/PubSubClient @ ^2.8


; File System Settings
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.4m2m.ld

; OTA settings
upload_protocol = espota
upload_port = mancave-esp8266.local


[env:nodemcu_wifi_test]
platform = espressif8266@^3.2.0
board = nodemcuv2
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    adafruit/Adafruit ADS1X15 @ ^2.4.0
    ArduinoJson @ ^6.21.3
    lorol/LittleFS_esp32 @ ^1.0.6
    knolleary/PubSubClient @ ^2.8


; File System Settings
board_build.filesystem = littlefs
board_build.ldscript = eagle.flash.4m2m.ld

; OTA settings
upload_protocol = espota
upload_port = test-esp8266.local