# [network]
# interfaces = odroidc4.network.lan
# interfaces = tuxedo.network.wifi

[odroidc4.network.lan]
name = lan
interface = end0

[tuxedo.network.wifi]
name = wifi
interface = wlo1

[displays]
# devices = odroidc4.display.hd44780

[gpio]
# devices = odroidc4.io
devices = mancave.io

[sensors]
# devices = odroidc4.sensor.dht22

[mqtt]
id = KestroMancave
host = mqtt.kestro.home
port = 1883
birth.messages = mqtt.discovery.homeassistant

[mqtt.discovery.homeassistant]
topic = homeassistant/device/rpi4_mancave/config
payload = {
        "device": {
            "identifiers": ["kestro_mancave"],
            "name": "Mancave",
            "model": "Raspberry Pi 4",
            "sw_version": "1.0.0",
            "suggested_area": "mancave"
        },
        "origin": {
            "name": "kestro-iot",
            "sw_version": "1.0.0"
        },
        "components": {
            "mancave_light_main": {
                "platform": "switch",
                "name": "Light Main",
                "icon": "mdi:lightbulb",
                "unique_id": "mancave_light_main",
                "command_topic": "kestro/mancave/light/main/control",
                "payload_on": "on",
                "payload_off": "off",
                "state_topic": "kestro/mancave/light/main/state",
                "retain": true
            },
            "mancave_light_gate": {
                "platform": "switch",
                "name": "Light Gate",
                "icon": "mdi:lightbulb",
                "unique_id": "mancave_light_gate",
                "command_topic": "kestro/mancave/light/gate/control",
                "payload_on": "on",
                "payload_off": "off",
                "state_topic": "kestro/mancave/light/gate/state",
                "retain": true
            },
            "mancave_light_attic": {
                "platform": "switch",
                "name": "Light Attic",
                "icon": "mdi:lightbulb",
                "unique_id": "mancave_light_attic",
                "command_topic": "kestro/mancave/light/attic/control",
                "payload_on": "on",
                "payload_off": "off",
                "state_topic": "kestro/mancave/light/attic/state",
                "retain": true
            },
            "outdoor_light_central": {
                "platform": "switch",
                "name": "Light Central Area",
                "icon": "mdi:lightbulb",
                "unique_id": "outdoor_light_central",
                "command_topic": "kestro/outdoor/light/central/control",
                "payload_on": "on",
                "payload_off": "off",
                "state_topic": "kestro/outdoor/light/central/state",
                "retain": true
            },
            "outdoor_light_camping": {
                "platform": "switch",
                "name": "Light Camping",
                "icon": "mdi:lightbulb",
                "unique_id": "outdoor_light_camping",
                "command_topic": "kestro/outdoor/light/camping/control",
                "payload_on": "on",
                "payload_off": "off",
                "state_topic": "kestro/outdoor/light/camping/state",
                "retain": true
            }
        }
    }


[mqtt.properties]
tuxedo.network.wifi = kestro/odroidc4/wifi
odroidc4.io.button1 = kestro/input/button1
odroidc4.io.led1 = kestro/output/led1
odroidc4.sensor.dht22 = kestro/sensor/temperature

[mqtt.states]
mancave.light.main = kestro/mancave/light/main/state
mancave.light.gate = kestro/mancave/light/gate/state
mancave.light.attic = kestro/mancave/light/attic/state
outdoor.light.central = kestro/outdoor/light/central/state
outdoor.light.camping = kestro/outdoor/light/camping/state

[mqtt.controls]
mancave.light.main = kestro/mancave/light/main/control
mancave.light.gate = kestro/mancave/light/gate/control
mancave.light.attic = kestro/mancave/light/attic/control
outdoor.light.central = kestro/outdoor/light/central/control
outdoor.light.camping = kestro/outdoor/light/camping/control


[odroidc4.display.ssd1306]
type = ssd1306
connection = i2c
address = 0x3C
width = 128
height = 32
text_format = {{ local_address }}\nKestro: {{ odroidc4_io_button1 }}


[odroidc4.display.hd44780]
type = hd44780
db0 = D8
db1 = D10
db2 = D12
db3 = D16
db4 = D18
db5 = D22
db6 = D26
db7 = D28
rs = D11
enable = D7
cols = 16
rows = 2
text_format = {{ local_address }}\nKestro

# [powersensor]
# type = ina260

[odroidc4.sensor.dht22]
type = dht22
pin = D7


# [distancesensor]
# type = hc-sr04
# trigger_pin = D15
# echo_pin = D13

[odroidc4.io]
type = mcp23017
address = 0x20
gpa7 = odroidc4.io.button1
gpb0 = odroidc4.io.led1

[odroidc4.io.button1]
mode = input
state = UP

[odroidc4.io.led1]
mode = output
value = false

[mancave.io]
type = board
D5 = mancave.light.main
D6 = mancave.light.gate
D13 = mancave.light.attic
D16 = outdoor.light.central
D19 = outdoor.light.camping
D20 = mancave.relay.channel.6
D21 = mancave.relay.channel.7
D26 = mancave.relay.channel.8

[mancave.light.main]
mode = output
value = false
invert_value = true

[mancave.light.gate]
mode = output
value = false
invert_value = true

[mancave.light.attic]
mode = output
value = false
invert_value = true

[outdoor.light.central]
mode = output
value = false
invert_value = true

[outdoor.light.camping]
mode = output
value = false
invert_value = true

[mancave.relay.channel.6]
mode = output
value = false
invert_value = true

[mancave.relay.channel.7]
mode = output
value = false
invert_value = true

[mancave.relay.channel.8]
mode = output
value = false
invert_value = true
