[display]
type = ssd1306
connection = i2c
address = 0x3C
width = 128
height = 32
text_format = {property[ip_addr]}\nKestro

# [powersensor]
# type = ina260

# [temperaturesensor]
# type = dht22
# pin = D7


# [distancesensor]
# type = hc-sr04
# trigger_pin = D15
# echo_pin = D13

[network]
lan = end0

