[network]
interfaces = odroidc4.network.lan
# interfaces = tuxedo.network.wifi

[odroidc4.network.lan]
name = lan
interface = end0

[tuxedo.network.wifi]
name = wifi
interface = wlo1

[displays]
devices = odroidc4.display.ssd1306

[gpio]
devices = odroidc4.io

[sensors]
devices = odroidc4.sensor.dht22

[mqtt]
id = KestroTesting
host = mqtt.kestro.home
port = 1883

[mqtt.propertytopics]
tuxedo.network.wifi = kestro/odroidc4/wifi
odroidc4.io.button1 = kestro/input/button1
odroidc4.io.led1 = kestro/output/led1
odroidc4.sensor.dht22 = kestro/sensor/temperature


[odroidc4.display.ssd1306]
type = ssd1306
connection = i2c
address = 0x3C
width = 128
height = 32
text_format = {{ local_address }}\nKestro: {{ odroidc4_io_button1 }}

# [powersensor]
# type = ina260

[odroidc4.sensor.dht22]
type = dht22
pin = D7


# [distancesensor]
# type = hc-sr04
# trigger_pin = D15
# echo_pin = D13

[odroidc4.io]
type = mcp23017
address = 0x20
gpa7 = odroidc4.io.button1
gpb0 = odroidc4.io.led1

[odroidc4.io.button1]
mode = input
state = UP

[odroidc4.io.led1]
mode = output
value = false

