
### GET GPIO statuses
GET http://{{host}}:{{port}}/api/kestro/peripherals/gpios

### GET GPIO status
GET http://{{host}}:{{port}}/api/kestro/peripherals/gpios/odroidc4.io.button1

### Set GPIO on
POST http://{{host}}:{{port}}/api/kestro/peripherals/gpios/odroidc4.io.led1/on

### Set GPIO off
POST http://{{host}}:{{port}}/api/kestro/peripherals/gpios/odroidc4.io.led1/off


### Toggle GPIO
POST http://{{host}}:{{port}}/api/kestro/peripherals/gpios/odroidc4.io.led1/toggle



### Toggle GPIO
POST http://{{host}}:{{port}}/api/kestro/peripherals/gpios/mancave.light.main/toggle

### Set GPIO on
POST http://{{host}}:{{port}}/api/kestro/peripherals/gpios/mancave.light.main/on
